development:
    secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
    db_user: root
    db_password: newPass
    DEVISE_JWT_SECRET_KEY: <%= ENV["SECRET_KEY_BASE"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  db_user: root
  db_password: newPass
  DEVISE_JWT_SECRET_KEY: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>